### ISSUE TITLE
User's owned data management: Event, nickname

### ISSUE THREAD

**Issue by angelagilhotra** [angelagilhotra/convo-app#48]
- editing proposed events
- nickname
- ~editing rsvps~ 
- ~viewing rsvps~

**Comment by angelagilhotra** [comment]
- editing proposed events: from the event, if owner is signed in, display an edit button
- nickname: from the propose form and from the rsvp modal (a little edit button beside the signature)
- editing rsvps: a new page - that displays all the future and past events the logged in user is going to - ability to edit rsvp from the event page

**Comment by saintsal** [comment]
I quite like the lightness of the current profiles.  Signing in through magic link, updating name when people RSVP.  It doesn't feel like "oh another profile to sign up for"  Also the wallet login makes it a little lighter again too, without the wait for an email.

**Comment by angelagilhotra** [comment]
1. Events
     1. Do not display the [RSVP section on the right](https://i.imgur.com/mlk7476.png) on the event page, display RSVP statuses from all attendees instead
3. Nickname
    1. a new component representing Signature - takes `userId` or `address` as parameter, and checks if currently logged in user is the same as the param -> displays edit person if yes

**Comment by angelagilhotra** [comment]
![image](https://github.com/angelagilhotra/convo-app/assets/10832414/204c416c-3c5b-40d1-959b-191908ddf778)
